/* Database schema to keep the structure of entire database. */

CREATE TABLE animals (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    date_of_birth DATE,
    escape_attempts INT,
    neutered BOOLEAN,
    weight_kg DECIMAL,
    species_id INT,
    owners_id INT,
    PRIMARY KEY (id),
    CONSTRAINT fk_species
    FOREIGN KEY(species_id) 
	REFERENCES species(id),
    CONSTRAINT fk_owners
    FOREIGN KEY(owners_id) 
	REFERENCES owners(id)
);
CREATE TABLE owners (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    full_name VARCHAR(100),
    age INT,
    PRIMARY KEY(id)
);
CREATE TABLE species (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100),
    PRIMARY KEY (id)
);
