/* Database schema to keep the structure of entire database. */

CREATE TABLE animals (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    date_of_birth DATE,
    escape_attempts INT,
    neutered BOOLEAN,
    weight_kg DECIMAL,
    species_id INT,
    owners_id INT,
    PRIMARY KEY (id),
    CONSTRAINT fk_species
    FOREIGN KEY(species_id) 
	REFERENCES species(id),
    CONSTRAINT fk_owners
    FOREIGN KEY(owners_id) 
	REFERENCES owners(id)
);
CREATE TABLE owners (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    full_name VARCHAR(100),
    age INT,
    PRIMARY KEY(id)
);
CREATE TABLE species (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100),
    PRIMARY KEY (id)
);
CREATE TABLE vets (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(100),
    age INT,
    date_of_graduation DATE
);
CREATE TABLE specializations (
    vets_id INT,
    species_id INT,
    FOREIGN KEY (vets_id) REFERENCES vets(id),
    FOREIGN KEY (species_id) REFERENCES species(id)
);
CREATE TABLE visits (
    animals_id INT,
    vets_id INT,
    date_of_visit DATE,
    FOREIGN KEY (animals_id) REFERENCES animals(id),
    FOREIGN KEY (vets_id) REFERENCES vets(id)
);
